- .ado/pipelines/config/configuration.yaml
- src/infra/workload/releaseunit/main.tf
- src/infra/workload/releaseunit/modules/stamp/kubernetes.tf
See https://github.com/Azure/AlwaysOn-Foundational-Online/pull/149
> Drop AKS `addon_profile`

- docs/reference-implementation/DeployAndTest-DevOps-Design-Decisions.md
- docs/reference-implementation/DeployAndTest-DevOps-Zero-Downtime-Update-Strategy.md
Bringing changes from Online https://github.com/Azure/AlwaysOn-Foundational-Online/pull/150
> Deploy docs updates

- .ado/pipelines/config/variables-values-e2e.yaml
- .ado/pipelines/config/variables-values-int.yaml
- .ado/pipelines/config/variables-values-prod.yaml
See https://github.com/Azure/AlwaysOn-Foundational-Online/pull/155
> Add additional comments for `stampLocation` value changes

- .ado/pipelines/templates/jobs-smoke-testing.yaml
- src/testing/ui-test-playwright/cataloguserflow.spec.js
from https://github.com/Azure/AlwaysOn-Foundational-Online/pull/156
> Playwright timeout

- src/infra/workload/globalresources/cosmosdb.tf
Align with https://github.com/Azure/AlwaysOn-Foundational-Online/pull/159
> set type cosmos db diagnostics type explicitly

- .ado/pipelines/config/variables-values-e2e.yaml
- src/infra/README.md
Swedencentral successfully tested https://dev.azure.com/Mission-Critical/Connected/_build/results?buildId=541&view=results
Connected works since we are not deploying the SLO Function. That's why -Online does not currently work in Sweden
> Sweden greenlight

- docs/reference-implementation/Getting-Started.md
Clarify pre-reqs at the top of the article
> Add Owner permission in pre-reqs 

- .ado/pipelines/templates/stages-full-release.yaml
- .ado/pipelines/templates/steps-terraform-init.yaml
> Improved destroy

- src/app/AlwaysOn.UI/src/components/ItemPage.vue
Similar:
https://github.com/Azure/Mission-Critical-Online/pull/239/
> Rounding the average rating to two digits

- docs/reference-implementation/AppDesign-SLO-Availability.md
The same as https://github.com/Azure/Mission-Critical-Online/pull/245
> Making the game reference more universal

- docs/reference-implementation/Troubleshooting.md
See https://github.com/Azure/Mission-Critical-Online/pull/251
> add quota error to tsg

- src/app/charts/backgroundprocessor/templates/deployment.yaml
- src/app/charts/catalogservice/templates/deployment.yaml
- src/app/charts/healthservice/templates/deployment.yaml
The same as https://github.com/Azure/Mission-Critical-Online/pull/253
> Add polling file watcher

- .ado/pipelines/config/configuration.yaml
In alignment with https://github.com/Azure/Mission-Critical-Online/pull/252/files
> Update AKS to Kubernetes 1.22.6

- src/infra/workload/releaseunit/variables-e2e.tfvars
- src/infra/workload/releaseunit/variables-int.tfvars
> Scale down AKS nodes

- .ado/pipelines/templates/jobs-workload-deploy.yaml
- src/app/AlwaysOn.BackgroundProcessor/Dockerfile
- src/app/AlwaysOn.BackgroundProcessor/Program.cs
- src/app/AlwaysOn.CatalogService/Dockerfile
- src/app/AlwaysOn.CatalogService/Program.cs
- src/app/AlwaysOn.CatalogService/Startup.cs
- src/app/AlwaysOn.HealthService/Dockerfile
- src/app/AlwaysOn.HealthService/Program.cs
- src/app/AlwaysOn.HealthService/Startup.cs
- src/app/AlwaysOn.Shared/SysConfiguration.cs
- src/app/AlwaysOn.UI/README.md
- src/app/AlwaysOn.UI/public/config.js
- src/app/AlwaysOn.UI/src/main.js
- src/infra/workload/globalresources/application_insights.tf
- src/infra/workload/releaseunit/modules/stamp/keyvault-secrets.tf
- src/infra/workload/releaseunit/modules/stamp/variables.tf
- src/infra/workload/releaseunit/stamp.tf
- src/infra/workload/releaseunit/variables-e2e.tfvars
- src/infra/workload/releaseunit/variables-int.tfvars
- src/infra/workload/releaseunit/variables-prod.tfvars
- src/infra/workload/releaseunit/variables.tf
https://github.com/Azure/Mission-Critical-Online/pull/238
> Transition to use AppInsights connection string

- .ado/pipelines/config/configuration.yaml
- docs/reference-implementation/AppDesign-Application-Design.md
- src/app/charts/backgroundprocessor/Chart.yaml
- src/app/charts/backgroundprocessor/templates/pdb.yaml
- src/app/charts/catalogservice/Chart.yaml
- src/app/charts/catalogservice/templates/pdb.yaml
- src/app/charts/healthservice/Chart.yaml
- src/app/charts/healthservice/templates/pdb.yaml
- src/config/ingress/values.helm.yaml
See https://github.com/Azure/Mission-Critical-Online/pull/257 for more details.
> Add PodDisruptionBudgets

- src/app/AlwaysOn.UI/package-lock.json
- src/app/AlwaysOn.UI/package.json
https://github.com/Azure/Mission-Critical-Online/pull/286
> Correct semver

- src/infra/workload/globalresources/main.tf
- src/infra/workload/releaseunit/main.tf
> Upgrade terraform to 3.1

- .ado/pipelines/templates/jobs-configuration.yaml
- src/app/charts/catalogservice/templates/ingress.yaml
- src/app/charts/catalogservice/values.yaml
Ported from -Online. Successfully validated in e2e
> move nginx to its own Namespace

- .ado/pipelines/templates/jobs-configuration.yaml
- src/config/ingress-nginx/values.helm.yaml
- src/config/monitoring/container-azm-ms-agentconfig.yaml
port changes from https://github.com/Azure/Mission-Critical-Online/pull/302
> Improve ngnix logging

- src/config/ingress-nginx/values.helm.yaml
Alignment with https://github.com/Azure/Mission-Critical-Online/pull/310
> Change `ingress-nginx` health probe path

- src/app/AlwaysOn.UI/package-lock.json
- src/app/AlwaysOn.UI/package.json
Before component updates make it here, porting this fix from Online.
https://github.com/Azure/Mission-Critical-Online/pull/335
> Update vue-cli and fix the ajv along with it

- .ado/pipelines/README.md
- .ado/pipelines/azure-release-e2e.yaml
- .ado/pipelines/templates/jobs-init-sampledata.yaml
- .ado/pipelines/templates/jobs-workload-deploy.yaml
- .ado/pipelines/templates/stages-configure-frontdoor.yaml
- .ado/pipelines/templates/stages-full-release.yaml
- .ado/pipelines/templates/steps-terraform-apply.yaml
- .ado/scripts/SmokeTest.ps1
- docs/reference-implementation/Getting-Started.md
- src/app/AlwaysOn.CatalogService/README.md
- src/app/AlwaysOn.CatalogService/Startup.cs
- src/app/AlwaysOn.HealthService/Startup.cs
- src/app/charts/catalogservice/templates/ingress.yaml
- src/infra/workload/globalresources/alerts.tf
- src/infra/workload/globalresources/frontdoor.tf
- src/infra/workload/globalresources/monitoring_webtests.tf
- src/infra/workload/releaseunit/modules/stamp/monitoring_webtests.tf
Ported changes from PRs:
https://github.com/Azure/Mission-Critical-Online/pull/380
https://github.com/Azure/Mission-Critical-Online/pull/383
https://github.com/Azure/Mission-Critical-Online/pull/382
> Various ports from the Online reference implementation

- src/app/charts/backgroundprocessor/Chart.yaml
- src/app/charts/backgroundprocessor/templates/hpa.yaml
- src/app/charts/catalogservice/Chart.yaml
- src/app/charts/catalogservice/templates/hpa.yaml
- src/app/charts/healthservice/Chart.yaml
- src/infra/README.md
Porting
https://github.com/Azure/Mission-Critical-Online/pull/396
https://github.com/Azure/Mission-Critical-Online/pull/395
> Port HPA changes from Online

- src/config/monitoring/container-azm-ms-agentconfig.yaml
ported from https://github.com/Azure/Mission-Critical-Online/pull/398
> Enable container log v2 schema

- .ado/pipelines/templates/jobs-workload-deploy.yaml
- .ado/scripts/SmokeTest.ps1
- src/app/AlwaysOn.CatalogService/Startup.cs
- src/app/charts/backgroundprocessor/templates/deployment.yaml
- src/app/charts/backgroundprocessor/values.yaml
- src/app/charts/catalogservice/templates/deployment.yaml
- src/app/charts/catalogservice/templates/ingress.yaml
- src/app/charts/catalogservice/templates/service.yaml
- src/app/charts/catalogservice/values.yaml
- src/app/charts/healthservice/templates/deployment.yaml
- src/app/charts/healthservice/templates/ingress.yaml
- src/app/charts/healthservice/templates/service.yaml
- src/app/charts/healthservice/values.yaml
- src/config/ingress-nginx/values.helm.yaml
See PR https://github.com/Azure/Mission-Critical-Online/pull/403 and PR https://github.com/Azure/Mission-Critical-Online/pull/402 for more.
> Cleanup and optimize Helm charts

- .ado/pipelines/templates/jobs-workload-deploy.yaml
Port from online https://github.com/Azure/Mission-Critical-Online/pull/423
> Fix retry on certificate wait

- .ado/scripts/SmokeTest.ps1
https://github.com/Azure/Mission-Critical-Online/pull/425
> Smoketest: add https://

- docs/reference-implementation/OpProcedures-Operational-Procedures.md
alignment with https://github.com/Azure/Mission-Critical-Online/pull/433
> drop transient

- .ado/pipelines/config/configuration.yaml
- src/app/AlwaysOn.BackgroundProcessor/AlwaysOn.BackgroundProcessor.csproj
- src/app/AlwaysOn.BackgroundProcessor/Program.cs
- src/app/AlwaysOn.CatalogService/AlwaysOn.CatalogService.csproj
- src/app/AlwaysOn.CatalogService/Program.cs
- src/app/AlwaysOn.HealthService/AlwaysOn.HealthService.csproj
- src/app/AlwaysOn.HealthService/Program.cs
- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.Shared/SysConfiguration.cs
- src/app/AlwaysOn.UI/Dockerfile
- src/app/AlwaysOn.UI/package-lock.json
- src/app/AlwaysOn.UI/package.json
- src/infra/workload/globalresources/main.tf
- src/infra/workload/releaseunit/main.tf
- src/infra/workload/releaseunit/modules/stamp/keyvault-secrets.tf
Validated https://dev.azure.com/Mission-Critical/Connected/_build/results?buildId=1727&view=results
> Component updates July 2022

- docs/README.md
- docs/reference-implementation/Getting-Started-CLI.md
- docs/reference-implementation/README.md
From https://github.com/Azure/Mission-Critical-Online/pull/464
> Getting started guide split up

- .ado/pipelines/templates/stages-full-release.yaml
- src/app/charts/backgroundprocessor/templates/deployment.yaml
- src/app/charts/catalogservice/templates/deployment.yaml
- src/app/charts/healthservice/templates/deployment.yaml
- src/config/ingress-nginx/values.helm.yaml
- src/infra/README.md
- src/infra/workload/releaseunit/modules/stamp/kubernetes.tf
- src/infra/workload/releaseunit/modules/stamp/publicip.tf
- src/infra/workload/releaseunit/modules/stamp/variables.tf
- src/infra/workload/releaseunit/stamp.tf
- src/infra/workload/releaseunit/variables-e2e.tfvars
- src/infra/workload/releaseunit/variables-int.tfvars
- src/infra/workload/releaseunit/variables-prod.tfvars
- src/infra/workload/releaseunit/variables.tf
Validated https://dev.azure.com/Mission-Critical/Connected/_build/results?buildId=1744&view=results
Ported from https://github.com/Azure/Mission-Critical-Online/pull/466
> Adding AKS user node pool

- .ado/pipelines/azure-deploy-grafana.yaml
- src/infra/monitoring/grafana/Dockerfile
- src/infra/monitoring/grafana/terraform/stamps/app-service.tf
- src/infra/monitoring/grafana/terraform/stamps/variables.tf
See https://github.com/Azure/Mission-Critical-Online/pull/475
> Grafana 9.0.4

- .ado/pipelines/config/configuration.yaml
- .ado/pipelines/templates/jobs-deploy-configuration.yaml
- .ado/pipelines/templates/stages-full-release.yaml
Port from https://github.com/Azure/Mission-Critical-Online/pull/539
> Fix AKS fetch for deletion

- src/infra/README.md
https://github.com/Azure/Mission-Critical-Online/pull/543
> Adding central india

- docs/reference-implementation/Troubleshooting.md
Brinding over from Online.
https://github.com/Azure/Mission-Critical-Online/pull/542/
> Unauthorized error troubleshooting

- src/infra/workload/globalresources/main.tf
- src/infra/workload/releaseunit/main.tf
- src/infra/workload/releaseunit/modules/stamp/build_agent_private_endpoints.tf
- src/infra/workload/releaseunit/modules/stamp/keyvault.tf
- src/infra/workload/releaseunit/modules/stamp/network.tf
- src/infra/workload/releaseunit/modules/stamp/private_endpoints.tf
Update provider and make use of new features
> Terraform 3.19 updates

- .ado/pipelines/config/configuration.yaml
- src/app/AlwaysOn.BackgroundProcessor/AlwaysOn.BackgroundProcessor.csproj
- src/app/AlwaysOn.CatalogService/AlwaysOn.CatalogService.csproj
- src/app/AlwaysOn.HealthService/AlwaysOn.HealthService.csproj
- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.Tests/AlwaysOn.Tests.csproj
- src/app/AlwaysOn.UI/Dockerfile
- src/app/AlwaysOn.UI/package-lock.json
- src/infra/monitoring/grafana/Dockerfile
- src/infra/workload/globalresources/main.tf
- src/infra/workload/releaseunit/main.tf
> Component updates 05-09-2022

- src/infra/monitoring/grafana/terraform/globalresources/la-wpspace-config.tf
- src/infra/monitoring/grafana/terraform/stamps/la-wspace-config.tf
- src/infra/workload/globalresources/acr.tf
- src/infra/workload/globalresources/cosmosdb.tf
- src/infra/workload/globalresources/frontdoor.tf
- src/infra/workload/globalresources/storage.tf
- src/infra/workload/releaseunit/modules/stamp/eventhub.tf
- src/infra/workload/releaseunit/modules/stamp/keyvault.tf
- src/infra/workload/releaseunit/modules/stamp/kubernetes.tf
- src/infra/workload/releaseunit/modules/stamp/storage.tf
https://github.com/Azure/Mission-Critical-Online/pull/586
> Update terraform diag logs to log_category_types 

- .ado/pipelines/templates/jobs-deploy-configuration.yaml
- .ado/pipelines/templates/jobs-deploy-workload.yaml
- .ado/pipelines/templates/stages-full-release.yaml
Use `--admin` to prevent interactive logins. See https://github.com/Azure/Mission-Critical-Online/pull/605 for more.
> Use AKS `--admin` credentials

- .ado/pipelines/config/configuration.yaml
- .ado/pipelines/templates/jobs-smoke-testing.yaml
See issue https://github.com/Azure/Mission-Critical-Online/issues/598 and PR https://github.com/Azure/Mission-Critical-Online/pull/599 for more.
> fix node version used for playwright

- .ado/pipelines/config/configuration.yaml
- src/infra/workload/globalresources/main.tf
- src/infra/workload/releaseunit/main.tf
- src/infra/workload/releaseunit/modules/stamp/kubernetes.tf
See https://github.com/Azure/Mission-Critical-Online/pull/592 for more.
> Switch to Calico NP and updated to align with online RI

- src/infra/workload/globalresources/modules/stamp_monitoring/alerts.tf
- src/infra/workload/globalresources/modules/stamp_monitoring/application_insights.tf
- src/infra/workload/globalresources/modules/stamp_monitoring/locals.tf
- src/infra/workload/globalresources/modules/stamp_monitoring/log_analytics.tf
- src/infra/workload/releaseunit/modules/stamp/eventhub.tf
- src/infra/workload/releaseunit/modules/stamp/keyvault.tf
- src/infra/workload/releaseunit/modules/stamp/kubernetes.tf
- src/infra/workload/releaseunit/modules/stamp/locals.tf
- src/infra/workload/releaseunit/modules/stamp/network.tf
@sebader just a minor but I noticed during the review of PR #344 that it might make sense to simplify that by creating the string once instead of building the string in multiple places. Thoughts?
> cleanup prefix used

- .github/workflows/resetBranch.yml
- .github/workflows/updateDependabot.yml
This PR adds the two github action workflows we've in online.
> push github actions from online

- .ado/pipelines/templates/jobs-deploy-workload.yaml
@sebader please take a look if this works. It prints out the `$workloadNamespace` variable in its output to see if the value is set or not.
> Output $workloadNamespace in debug output

- .ado/pipelines/config/variables-values-e2e.yaml
old prefix is for whatever reason already in used.. switching to a new one for e2e
> change prefix

- src/infra/workload/releaseunit/modules/stamp/roleassignments.tf
> Add missing role assignments

- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/application_insights.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/globalresources/modules/stamp_monitoring/application_insights.tf
- src/infra/workload/globalresources/modules/stamp_monitoring/log_analytics.tf
- src/infra/workload/globalresources/modules/stamp_monitoring/variables.tf
- src/infra/workload/globalresources/monitoring.tf
- src/infra/workload/globalresources/monitoring_stamp.tf
- src/infra/workload/globalresources/variables.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
> Make LAW quota a variable and update tf

- .ado/pipelines/templates/jobs-deploy-configuration.yaml
same as https://github.com/Azure/Mission-Critical-Online/pull/899
> Move to new lb annotation

- src/app/AlwaysOn.BackgroundProcessor/AlwaysOn.BackgroundProcessor.csproj
- src/app/AlwaysOn.CatalogService/AlwaysOn.CatalogService.csproj
- src/app/AlwaysOn.HealthService/AlwaysOn.HealthService.csproj
- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.Tests/AlwaysOn.Tests.csproj
- src/app/AlwaysOn.UI/Dockerfile
- src/app/AlwaysOn.UI/package-lock.json
- src/infra/monitoring/grafana/Dockerfile
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
> Component updates April-2023

- src/app/charts/backgroundprocessor/templates/deployment.yaml
Based on conversation [here ](https://stackoverflow.com/a/75851556/1537195) there was a small bug in this logic
> Fix liveness probe

- src/infra/build-agents/main.bicep
Fixed linter warnings regarding use of parent property.
> Fixed linter warnings regarding use of parent

- src/ops/scripts/Clean-StaleResources.ps1
remove "value", seems like the CLI output was changed
> Fix saved la searched

- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.Tests/AlwaysOn.Tests.csproj
- src/app/AlwaysOn.UI/package-lock.json
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
> Component updates July-2023

- src/infra/monitoring/grafana/terraform/globalresources/la-wpspace-config.tf
- src/infra/monitoring/grafana/terraform/stamps/la-wspace-config.tf
- src/infra/workload/globalresources/acr.tf
- src/infra/workload/globalresources/cosmosdb.tf
- src/infra/workload/globalresources/frontdoor.tf
- src/infra/workload/globalresources/storage.tf
- src/infra/workload/releaseunit/modules/stamp/eventhub.tf
- src/infra/workload/releaseunit/modules/stamp/keyvault.tf
- src/infra/workload/releaseunit/modules/stamp/kubernetes.tf
- src/infra/workload/releaseunit/modules/stamp/storage.tf
Replace deprecated `log` argument with `enabled_log`.
> Replace deprecated `log` argument with `enabled_log`

- .ado/pipelines/config/configuration.yaml
- src/infra/monitoring/grafana/terraform/globalresources/la-wpspace-config.tf
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/la-wspace-config.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/acr.tf
- src/infra/workload/globalresources/cosmosdb.tf
- src/infra/workload/globalresources/frontdoor.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/globalresources/storage.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
- src/infra/workload/releaseunit/modules/stamp/eventhub.tf
- src/infra/workload/releaseunit/modules/stamp/keyvault.tf
- src/infra/workload/releaseunit/modules/stamp/kubernetes.tf
- src/infra/workload/releaseunit/modules/stamp/storage.tf
See https://github.com/Azure/Mission-Critical-Online/pull/1019 and https://github.com/Azure/Mission-Critical-Online/issues/1018
> Fix issues and port over changes from the online RI

- .ado/pipelines/config/configuration.yaml
- .github/workflows/resetBranch.yml
- .github/workflows/updateDependabot.yml
- src/app/AlwaysOn.BackgroundProcessor/AlwaysOn.BackgroundProcessor.csproj
- src/app/AlwaysOn.CatalogService/AlwaysOn.CatalogService.csproj
- src/app/AlwaysOn.HealthService/AlwaysOn.HealthService.csproj
- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.Tests/AlwaysOn.Tests.csproj
- src/app/AlwaysOn.UI/package-lock.json
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
validated in https://dev.azure.com/mission-critical/Connected/_build/results?buildId=3107&view=results
> Component updates 10-2023

- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.UI/package-lock.json
- src/app/AlwaysOn.UI/package.json
- src/infra/monitoring/grafana/Dockerfile
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
> Component updates Nov-2023

- .ado/pipelines/config/configuration.yaml
- src/app/AlwaysOn.BackgroundProcessor/AlwaysOn.BackgroundProcessor.csproj
- src/app/AlwaysOn.BackgroundProcessor/Dockerfile
- src/app/AlwaysOn.CatalogService/AlwaysOn.CatalogService.csproj
- src/app/AlwaysOn.CatalogService/Dockerfile
- src/app/AlwaysOn.HealthService/AlwaysOn.HealthService.csproj
- src/app/AlwaysOn.HealthService/Dockerfile
- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.Tests/AlwaysOn.Tests.csproj
- src/app/AlwaysOn.Tests/ControllerTests/CatalogItemControllerTests.cs
- src/app/AlwaysOn.UI/package-lock.json
- src/infra/monitoring/grafana/Dockerfile
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
> Component updates Dec-2023

- src/infra/monitoring/grafana/config/grafana.ini
> Remove sample grafana key

- src/app/AlwaysOn.BackgroundProcessor/AlwaysOn.BackgroundProcessor.csproj
- src/app/AlwaysOn.BackgroundProcessor/Program.cs
- src/app/AlwaysOn.CatalogService/AlwaysOn.CatalogService.csproj
- src/app/AlwaysOn.CatalogService/Startup.cs
- src/app/AlwaysOn.HealthService/AlwaysOn.HealthService.csproj
- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.UI/Dockerfile
- src/app/AlwaysOn.UI/package-lock.json
- src/app/AlwaysOn.UI/package.json
- src/infra/monitoring/grafana/Dockerfile
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
> Component updates Jan-2024

- .ado/pipelines/config/configuration.yaml
- src/app/AlwaysOn.BackgroundProcessor/AlwaysOn.BackgroundProcessor.csproj
- src/app/AlwaysOn.CatalogService/AlwaysOn.CatalogService.csproj
- src/app/AlwaysOn.HealthService/AlwaysOn.HealthService.csproj
- src/app/AlwaysOn.Shared/AlwaysOn.Shared.csproj
- src/app/AlwaysOn.UI/Dockerfile
- src/app/AlwaysOn.UI/package-lock.json
- src/app/AlwaysOn.UI/package.json
- src/infra/monitoring/grafana/Dockerfile
- src/infra/monitoring/grafana/terraform/globalresources/main.tf
- src/infra/monitoring/grafana/terraform/stamps/main.tf
- src/infra/workload/globalresources/main.tf
- src/infra/workload/ingress_private_connections/main.tf
- src/infra/workload/releaseunit/main.tf
Some component-updates to catch up with the online reference implementation.
> Component updates - February 5th 2024

- .github/workflows/codeql.yml
- .github/workflows/defender-for-devops.yml
- .github/workflows/devskim.yml
Enable code scanning based on enhanced security requirements. Copy from MC-online repo.
> Enable code scanning
